/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpanalyser.truthtable;

import com.quew8.ttg.MainController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Vlastimil Kapusta, xkapus02@stud.fit.vutbr.cz
 */
public class DialogTruthTable extends javax.swing.JDialog {

   private List<String> header;
   private List<List<String>> data;

   /**
    * Creates new form DialogTruthTable
    */
   public DialogTruthTable(java.awt.Frame parent, boolean modal, String expression, int generation) {
      super(parent, modal);
      data = new ArrayList<>();
      header = new ArrayList<>();
      String usedInputs = TruthTableUtils.getUsedInputs(expression);
      expression = "O = " + expression + "[" + usedInputs + "]";

      //System.out.println("expression" + expression);
      MainController mC = new MainController();
      try {
         mC.generateTT(expression, header, data);
      } catch (RuntimeException e) {
         System.out.println(e.getMessage());
      }

      //TruthTableUtils.printList(header);
      //TruthTableUtils.print2DList(data);
      initComponents();
      centerTable(tableTruth);

      setTitle("Truth Table | Generation " + generation);
      
      pack();
      setVisible(true);
   }

   private void centerTable(JXTable table) {
      centerTableHeader(table);
      for (int i = 0; i < table.getColumnCount(); i++) {
         centerCol(table, i);
      }
   }

   /**
    * vycentruje hlavicku tabulky
    *
    * @param table Tabulka pro centrovani hlavicky
    */
   private void centerTableHeader(JXTable table) {
      TableCellRenderer rendererFromHeader = table.getTableHeader().getDefaultRenderer();
      JLabel headerLabel = (JLabel) rendererFromHeader;
      headerLabel.setHorizontalAlignment(JLabel.CENTER);
   }

   /**
    * vycentrovani sloupce tabulky
    *
    * @param col sloupec
    */
   private void centerCol(JXTable table, int col) {
      DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
      centerRenderer.setHorizontalAlignment(JLabel.CENTER);
      table.getColumnModel().getColumn(col).setCellRenderer(centerRenderer);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane2 = new javax.swing.JScrollPane();
      tableTruth = new org.jdesktop.swingx.JXTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Truth Table");

      tableTruth.setModel(new ListTableModel(header, data));
      tableTruth.setDoubleBuffered(true);
      tableTruth.setEditable(false);
      tableTruth.setEnabled(false);
      tableTruth.setRowSelectionAllowed(false);
      tableTruth.setSortable(false);
      jScrollPane2.setViewportView(tableTruth);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(DialogTruthTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(DialogTruthTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(DialogTruthTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(DialogTruthTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            DialogTruthTable dialog = new DialogTruthTable(new javax.swing.JFrame(), true, null, 0);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
               @Override
               public void windowClosing(java.awt.event.WindowEvent e) {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane2;
   private org.jdesktop.swingx.JXTable tableTruth;
   // End of variables declaration//GEN-END:variables

}
